package tiptaptoe;

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 50494
 */
public class Jueguito extends javax.swing.JFrame {

    /**
     * Creates new form Jueguito
     */
    public Jueguito() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tablero = new javax.swing.JPanel();
        button00 = new javax.swing.JButton();
        button01 = new javax.swing.JButton();
        button12 = new javax.swing.JButton();
        button02 = new javax.swing.JButton();
        button10 = new javax.swing.JButton();
        button11 = new javax.swing.JButton();
        button20 = new javax.swing.JButton();
        button21 = new javax.swing.JButton();
        button22 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("P1: Turno de X || P2: Turno de Y");

        tablero.setBackground(new java.awt.Color(255, 102, 255));
        tablero.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 255), 3, true));
        tablero.setForeground(new java.awt.Color(255, 102, 255));
        tablero.setLayout(new java.awt.GridLayout(3, 3));

        button00.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button00.setToolTipText("");
        button00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button00ActionPerformed(evt);
            }
        });
        tablero.add(button00);

        button01.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button01.setToolTipText("");
        button01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button01ActionPerformed(evt);
            }
        });
        tablero.add(button01);

        button12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button12.setToolTipText("");
        button12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button12ActionPerformed(evt);
            }
        });
        tablero.add(button12);

        button02.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button02.setToolTipText("");
        button02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button02ActionPerformed(evt);
            }
        });
        tablero.add(button02);

        button10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button10.setToolTipText("");
        button10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button10ActionPerformed(evt);
            }
        });
        tablero.add(button10);

        button11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button11.setToolTipText("");
        button11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button11ActionPerformed(evt);
            }
        });
        tablero.add(button11);

        button20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button20.setToolTipText("");
        button20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button20ActionPerformed(evt);
            }
        });
        tablero.add(button20);

        button21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button21.setToolTipText("");
        button21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button21ActionPerformed(evt);
            }
        });
        tablero.add(button21);

        button22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button22.setToolTipText("");
        button22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button22ActionPerformed(evt);
            }
        });
        tablero.add(button22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(tablero, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tablero, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button12ActionPerformed
        // TODO add your handling code here:
        char[][] tablero = new char[3][3];
        
        if (turno % 2 == 0) {
        button12.setEnabled(false); 
        button12.setText("X");     
        button12.setText("x");      
        tablero[1][2] = 'x';       
    } else {
        button02.setEnabled(false); 
        button02.setText("O");      
        tablero[1][2] = 'o';        
    }
         button12.setEnabled(false);
         turno++;
         deshabilitarBotones();
        
        if (ganador('o')) {
        JOptionPane.showMessageDialog(this, "¡Jugador O gano!");
       
    } else if (ganador('x')) {
        JOptionPane.showMessageDialog(this, "¡Jugador X gano!");
       
       
    }
    }//GEN-LAST:event_button12ActionPerformed

    private int turno = 0;
    private void button00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button00ActionPerformed
        // TODO add your handling code here:
        char[][] tablero = new char[3][3];
        
        if (turno % 2 == 0) {
        button00.setEnabled(false); 
        button00.setText("X");     
        button00.setText("x");      
        tablero[0][0] = 'x';       
    } else {
        button00.setEnabled(false); 
        button00.setText("O");      
        tablero[0][0] = 'o';        
    }
         button00.setEnabled(false);
         turno++;
        
        if (ganador('o')) {
        JOptionPane.showMessageDialog(this, "¡Jugador O gano!");
       
    } else if (ganador('x')) {
        JOptionPane.showMessageDialog(this, "¡Jugador X gano!");
        deshabilitarBotones();
       
    }
        
    }//GEN-LAST:event_button00ActionPerformed

    private void button02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button02ActionPerformed
        // TODO add your handling code here:
        char[][] tablero = new char[3][3];
        
        if (turno % 2 == 0) {
        button02.setEnabled(false); 
        button02.setText("X");     
        button02.setText("x");      
        tablero[0][2] = 'x';       
    } else {
        button02.setEnabled(false); 
        button02.setText("O");      
        tablero[0][2] = 'o';        
    }
         button02.setEnabled(false);
         turno++;
        
        if (ganador('o')) {
        JOptionPane.showMessageDialog(this, "¡Jugador O gano!");
       
    } else if (ganador('x')) {
        JOptionPane.showMessageDialog(this, "¡Jugador X gano!");
        deshabilitarBotones();
       
    }
    

    }//GEN-LAST:event_button02ActionPerformed

    private void button20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button20ActionPerformed
        // TODO add your handling code here:
        char[][] tablero = new char[3][3];
        
        if (turno % 2 == 0) {
        button20.setEnabled(false); 
        button20.setText("X");     
        button20.setText("x");      
        tablero[2][0] = 'x';       
    } else {
        button20.setEnabled(false); 
        button20.setText("O");      
        tablero[2][0] = 'o';        
    }
         button20.setEnabled(false);
         turno++;
        
        if (ganador('o')) {
        JOptionPane.showMessageDialog(this, "¡Jugador O ganó!");
       
    } else if (ganador('x')) {
        JOptionPane.showMessageDialog(this, "¡Jugador X ganó!");
       
    }
    

    }//GEN-LAST:event_button20ActionPerformed

    private void button01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button01ActionPerformed
        // TODO add your handling code here:
        char[][] tablero = new char[3][3];
        
        if (turno % 2 == 0) {
        button01.setEnabled(false); 
        button01.setText("X");     
        button01.setText("x");      
        tablero[0][1] = 'x';       
    } else {
        button01.setEnabled(false); 
        button01.setText("O");      
        tablero[0][1] = 'o';        
    }
         button01.setEnabled(false);
         turno++;
        
        if (ganador('o')) {
        JOptionPane.showMessageDialog(this, "¡Jugador O ganó!");
       
    } else if (ganador('x')) {
        JOptionPane.showMessageDialog(this, "¡Jugador X ganó!");
       
    }
   

    }//GEN-LAST:event_button01ActionPerformed

    private void button10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button10ActionPerformed
        // TODO add your handling code here:
        char[][] tablero = new char[3][3];
        
        if (turno % 2 == 0) {
        button10.setEnabled(false); 
        button10.setText("X");     
        button10.setText("x");      
        tablero[1][0] = 'x';       
    } else {
        button10.setEnabled(false); 
        button10.setText("O");      
        tablero[1][0] = 'o';        
    }
         button10.setEnabled(false);
         turno++;
        
        if (ganador('o')) {
        JOptionPane.showMessageDialog(this, "¡Jugador O ganó!");
       
    } else if (ganador('x')) {
        JOptionPane.showMessageDialog(this, "¡Jugador X ganó!");
       
    }
    

    }//GEN-LAST:event_button10ActionPerformed

    private void button21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button21ActionPerformed
        // TODO add your handling code here:
        char[][] tablero = new char[3][3];
        
        if (turno % 2 == 0) {
        button21.setEnabled(false); 
        button21.setText("X");     
        button21.setText("x");      
        tablero[2][1] = 'x';       
    } else {
        button21.setEnabled(false); 
        button21.setText("O");      
        tablero[2][1] = 'o';        
    }
         button21.setEnabled(false);
         turno++;
        
        if (ganador('o')) {
        JOptionPane.showMessageDialog(this, "¡Jugador O ganó!");
       
    } else if (ganador('x')) {
        JOptionPane.showMessageDialog(this, "¡Jugador X ganó!");
       
    }
   


    }//GEN-LAST:event_button21ActionPerformed

    private void button11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button11ActionPerformed
        // TODO add your handling code here:
        char[][] tablero = new char[3][3];
        
        if (turno % 2 == 0) {
        button11.setEnabled(false); 
        button11.setText("X");     
        button11.setText("x");      
        tablero[1][1] = 'x';       
    } else {
        button11.setEnabled(false); 
        button11.setText("O");      
        tablero[0][2] = 'o';        
    }
         button11.setEnabled(false);
         turno++;
        
        if (ganador('o')) {
        JOptionPane.showMessageDialog(this, "¡Jugador O gano!");
       
    } else if (ganador('x')) {
        JOptionPane.showMessageDialog(this, "¡Jugador X gano!");
       
    }
    }//GEN-LAST:event_button11ActionPerformed

    private void button22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button22ActionPerformed
        // TODO add your handling code here:
        char[][] tablero = new char[3][3];
        
        if (turno % 2 == 0) {
        button22.setEnabled(false); 
        button22.setText("X");     
        button22.setText("x");      
        tablero[2][2] = 'x';       
    } else {
        button22.setEnabled(false); 
        button22.setText("O");      
        tablero[12[2] = 'o';        
    }
         button22.setEnabled(false);
         turno++;
        
        if (ganador('o')) {
        JOptionPane.showMessageDialog(this, "¡Jugador O gano!");
       
    } else if (ganador('x')) {
        JOptionPane.showMessageDialog(this, "¡Jugador X gano!");
       
    }
    }//GEN-LAST:event_button22ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Jueguito().setVisible(true);
            }
            boolean ganador(char icono){
                for (int i = 0; i < 3; i++) {
                    if((tablero[i][0]==icono)&&(tablero[i][1]==icono)&&(tablero[i][2]==icono)){
                        return true;
                    }
                    
                    if((tablero[0][i]==icono)&&(tablero[1][i]==icono)&&(tablero[2][i]==icono)){
                        return true;
                    }
                    
                }
                if((tablero[1][1]==icono)&&(tablero[2][2]==icono)&&(tablero[0][0]==icono)){
                    return true;
                    }
                return (tablero[0][2]==icono)&&(tablero[1][1]==icono)&&(tablero[2][0]==icono);
            
            }
            char [][]tablero = new char[3][3];
            
        });
        
        
            
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button00;
    private javax.swing.JButton button01;
    private javax.swing.JButton button02;
    private javax.swing.JButton button10;
    private javax.swing.JButton button11;
    private javax.swing.JButton button12;
    private javax.swing.JButton button20;
    private javax.swing.JButton button21;
    private javax.swing.JButton button22;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel tablero;
    // End of variables declaration//GEN-END:variables

    private boolean ganador(char c) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void verificarEstado() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void deshabilitarBotones() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    
        
}
